### ISSUE TITLE
libbpf: map 'simple_ops': failed to create: Operation not supported(-95)

### ISSUE THREAD

**Issue by EdLovecraft** [sched-ext/sched_ext#12]
```
❯ sudo ./scx_example_simple
libbpf: map 'simple_ops': failed to create: Operation not supported(-95)
libbpf: failed to load object 'scx_example_simple'
libbpf: failed to load BPF skeleton 'scx_example_simple': -95
scx_example_simple: scx_example_simple.c:83: int main(int, char **): Assertion `!scx_example_simple__load(skel)' failed.
[1]    26428 IOT instruction  sudo ./scx_example_simple
```

**Comment by ByteLab-David** [comment]
@anakryiko this seems to be a fallout from https://github.com/sched-ext/sched_ext/commit/0db0ad6defeacfc957cc3f7394a17870bf1ad16a. I tested it locally and it seemed to work, but maybe I made a mistake because this is now happening to me as well. Did we need any commits for this beyond https://github.com/sched-ext/sched_ext/commit/8d1608d70927747da9c1a8770edf7b6ee68f8ebc?

**Comment by ByteLab-David** [comment]
Let me revert 0db0ad6defeacfc957cc3f7394a17870bf1ad16a for now and then we can continue figuring out what the issue was.

**Comment by ByteLab-David** [comment]
@EdLovecraft can you try pulling the latest commit again and rebuilding the schedulers, and seeing if that fixes it for you?

**Comment by EdLovecraft** [comment]
> @EdLovecraft can you try pulling the latest commit again and rebuilding the schedulers, and seeing if that fixes it for you?

@Decave  Fixed, thank you

**Comment by ByteLab-David** [comment]
I'm going to try rebasing on top of the latest bpf-next master branch to see if that fixes it. That seems useful regardless in preparation for v4 of the patch set. Unfortunately, it seems that bpf-next master fails to boot at the moment, so it might take some time today to figure this out.

**Comment by ByteLab-David** [comment]
> I'm going to try rebasing on top of the latest bpf-next master branch to see if that fixes it. That seems useful regardless in preparation for v4 of the patch set. Unfortunately, it seems that bpf-next master fails to boot at the moment, so it might take some time today to figure this out.

This is due to https://lore.kernel.org/all/7194ed8a989a85b98d92e62df660f4a90435a723.1681342859.git.jpoimboe@kernel.org/, which only affects clang-17, so I think we should be fine. I'm going to send out a PR for the rebase soon, but even with the rebase, it looks like `.struct_ops.link` on the map still causes us to fail to load. More investigation required.
