### ISSUE TITLE
Schedulers do not compile since some time

### ISSUE THREAD

**Issue by ptr1337** [sched-ext/sched_ext#58]
Hey together,

I am maintaining the AUR package and im not able to compile the tools/schedulers.

Following commands to reproduce on a archlinux based machine:

```
git clone https://github.com/sched-ext/sched_ext.git
cd sched_ext/sched_ext/tools/sched_ext
make CC=clang LLVM=1 -j
```

The full log can be found here:
https://paste.cachyos.org/p/2b689a6.log

Versions:
gcc -v:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/pkg/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.1 20230801 (GCC) 
```
clang -v:
```
clang version 16.0.6 (https://gitlab.archlinux.org/archlinux/packaging/packages/clang.git ff762c61c53dca880df8ed701c1bf9c73117e675)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

rust was the 1.73.0 from the arch repository (https://archlinux.org/packages/extra/x86_64/rust/)
and also with rustup the 1.70.0 was tested (including beta, nightly and stable via rustup)

uname -a

```
Linux ptr1337-cachyos 6.6.0-rc2-2-sched-ext-git-gfbac810e36ed #1 SMP PREEMPT_DYNAMIC Wed, 11 Oct 2023 18:34:39 +0000 x86_64 GNU/Linux
```

**Comment by ByteLab-David** [comment]
Thanks for the report. I'll take a look at this soon. Maybe it will be magically resolved once we take care of https://github.com/sched-ext/sched_ext/issues/56

**Comment by ByteLab-David** [comment]
@ptr1337 I did take a quick look at the build output, and at first glance it looks like you don't have an up-to-date vmlinux.h file. The scheduler build system creates the vmlinux.h file by doing the following:

1. First finding a vmlinux compiled with BTF that it can use to create a vmlinux.h file. You can see the order it searches in here: https://github.com/sched-ext/sched_ext/blob/sched_ext/tools/sched_ext/Makefile#L68-L72.
2. Invoking `bpftool btf dump file <vmlinux found in step (1)> format c > include/vmlinux.h`

It's that vmlinux.h file that the schedulers use to find the types that they're not able to find in your paste output. Note that if you're compiling the schedulers in-tree, it would be sufficient to first compile the kernel with all the necessary .config options, as it will find the vmlinux file to create the vmlinux.h at `/path/to/tree/tools/sched_ext/../../vmlinux`. Otherwise it will look in `/sys/kernel/btf/vmlinux` or `/boot/vmlinux-$(uname -r)`. If that vmlinux is out of date, you won't get a vmlinux.h file that has all of the types that the BPF programs need.

**Comment by ByteLab-David** [comment]
I might not have time until a bit later in the week, but I'll try to update https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-sched-ext-git to accommodate the above described workflow.

**Comment by ptr1337** [comment]
Hi David,

Thanks, i will look into this tomorrow! I will keep you reported

**Comment by ptr1337** [comment]
Hi @Decave ,

I got it running. I will fixup the AUR Package, so that people can build it on their own.

Edit:
It seems like it needs to be build at the same build process and can not be build like a "standalone" system.
Probably I missed that :p

**Comment by ptr1337** [comment]
Should be good now:
https://aur.archlinux.org/cgit/aur.git/commit/?h=linux-sched-ext-git&id=0b1deb60ec2f123d68dfcb7b3a5d9fe646c3518a

Edit:
I have included the nest scheduler, which is precompiled for testing reasons.
